package com.taskvortex.entity;

public enum TaskStatus {
    NOT_STARTED,
    DEVELOPMENT_IN_PROGRESS,
    DEVELOPMENT_COMPLETE,
    RE_DEVELOPMENT_IN_PROGRESS,
    TESTING_IN_PROGRESS,
    TESTING_COMPLETE,
    RE_TESTING_IN_PROGRESS,
    IN_UAT,
    DEPLOYMENT_COMPLETE,
    HOLD,
    CANCELLED
}